version: '3.8'

services:
  tmpserver:
    image: tmpserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    hostname: mytmpserver
    restart: unless-stopped